name: Generate Snake

on:
  # Her gece çalışsın
  schedule:
    - cron: "0 0 * * *"
  # Elle de tetikleyebilirsin
  workflow_dispatch:
  # README veya ayar değişince de çalışsın
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: h4mz1fy
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github-light

      - name: Publish to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
